### ISSUE TITLE
Create a scafolding files for typescript-react

### ISSUE THREAD

**Issue by shrijan00003** [shrijan00003/react-feature-cli#1]
- list of the files and folder that have to be created with typescript-react

**Comment by akasrai** [comment]
Hi @shrijan00003, I have added this feature and created a PR #8 . Please review and merge if it meets the requirement.

**Comment by shrijan00003** [comment]
> Hi @shrijan00003, I have added this feature and created a PR #8. Please review and merge if it meets the requirement.

Thank you so much for your contribution, PR is already merged, will decide to close this issue asap
